// <auto-generated />
using System;
using IMS.DomainModel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IMS.Web.Migrations
{
    [DbContext(typeof(IMSDbContext))]
    [Migration("20190402045445_added_column_isArchived_in_student_basic_information")]
    partial class added_column_isArchived_in_student_basic_information
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IMS.DomainModel.Models.AdministrationCity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("StateId");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("AdministrationCities");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.AdministrationCountry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<int>("InstituteId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("InstituteId");

                    b.ToTable("AdministrationCountries");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.AdministrationCurrency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("CurrencyName")
                        .IsRequired();

                    b.Property<int>("InstituteId");

                    b.Property<string>("Symbol")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("InstituteId");

                    b.ToTable("AdministrationCurrencies");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.AdministrationEmailConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("EnableSsl");

                    b.Property<string>("HostName")
                        .IsRequired();

                    b.Property<int>("InstituteId");

                    b.Property<string>("MailPassword")
                        .IsRequired();

                    b.Property<string>("MailUserName")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("PortNumber");

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<string>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("InstituteId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("AdministrationEmailConfigurations");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.AdministrationState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CountryId");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("AdministrationStates");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool?>("ForgotPasswordInitiated");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime>("UpdatedOn");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.AutoSequenceGenerator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AutoSequenceGeneratorType");

                    b.Property<string>("CreatedById");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("CustomText");

                    b.Property<int>("InstituteId");

                    b.Property<int>("Seperator");

                    b.Property<string>("UpdateById");

                    b.Property<DateTime>("UpdateDate");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("InstituteId");

                    b.HasIndex("UpdateById");

                    b.ToTable("AutoSequenceGenerators");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.AutoSequenceGeneratorDataType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AutoSequenceGeneratorId");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("IsSelected");

                    b.Property<int>("Length");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("OrderId");

                    b.HasKey("Id");

                    b.HasIndex("AutoSequenceGeneratorId");

                    b.ToTable("AutoSequenceGeneratorDataTypes");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.BloodGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<int>("InstituteId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("Status");

                    b.HasKey("Id");

                    b.HasIndex("InstituteId");

                    b.ToTable("BloodGroups");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.Caste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<int>("InstituteId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("Status");

                    b.HasKey("Id");

                    b.HasIndex("InstituteId");

                    b.ToTable("Castes");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("DepartmentName")
                        .IsRequired();

                    b.Property<int>("InstituteId");

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<string>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("InstituteId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.Designation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("DesignationName")
                        .IsRequired();

                    b.Property<int>("InstituteId");

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<string>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("InstituteId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Designations");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<int>("InstituteId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("Status");

                    b.HasKey("Id");

                    b.HasIndex("InstituteId");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AcademicYearId");

                    b.Property<int?>("CompanyWbs");

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<DateTime>("HolidayDate");

                    b.Property<DateTime?>("HolidayToDate");

                    b.Property<int>("InstitutionId");

                    b.Property<int>("OccuranceType");

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.Institute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Location");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Institutes");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.InstituteAcademicYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AcademicYearCode")
                        .IsRequired();

                    b.Property<string>("ChallanStartingNumber")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int?>("CompanyWbs");

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<string>("CreatedByUserId");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime>("FromDate");

                    b.Property<int>("InstituteId");

                    b.Property<bool>("IsActive");

                    b.Property<DateTime>("ToDate");

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("InstituteId");

                    b.ToTable("InstituteAcademicYears");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.InstituteBccCcEmailMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<int>("InstituteId");

                    b.Property<bool>("IsBcc");

                    b.HasKey("Id");

                    b.HasIndex("InstituteId");

                    b.ToTable("InstituteBccCcEmailMappings");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.InstituteClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ClassOrder");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<double>("Duration");

                    b.Property<int>("DurationUnit");

                    b.Property<string>("GroupCode")
                        .IsRequired();

                    b.Property<int>("InstituteId");

                    b.Property<bool>("IsGroup");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("NumberOfFeeTerms");

                    b.HasKey("Id");

                    b.HasIndex("InstituteId");

                    b.ToTable("InstituteClasses");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.InstituteClassSubjectMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AlternateFacultyId");

                    b.Property<int>("ClassId");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<int>("FacultyId");

                    b.Property<int>("SubjectId");

                    b.HasKey("Id");

                    b.HasIndex("AlternateFacultyId");

                    b.HasIndex("ClassId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("SubjectId");

                    b.ToTable("InstituteClassSubjectMappings");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.InstituteLanguageMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<int>("InstituteId");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("InstituteId");

                    b.ToTable("InstituteLanguageMasters");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.InstituteNationality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<int>("InstituteId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("Status");

                    b.HasKey("Id");

                    b.HasIndex("InstituteId");

                    b.ToTable("InstituteNationalities");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.InstituteRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<int>("InstituteId");

                    b.Property<string>("RoleName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("InstituteId");

                    b.ToTable("InstituteRoles");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.InstituteSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<int>("InstituteId");

                    b.Property<bool>("IsGroup");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("InstituteId");

                    b.ToTable("InstituteSubjects");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<int>("InstituteId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("Status");

                    b.HasKey("Id");

                    b.HasIndex("InstituteId");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.LookUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<int>("InstituteId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("Status");

                    b.HasKey("Id");

                    b.HasIndex("InstituteId");

                    b.ToTable("LookUps");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.LookUpMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<bool>("IsDefault");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsSystemRow");

                    b.Property<int>("LookUpId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("Status");

                    b.HasKey("Id");

                    b.HasIndex("LookUpId");

                    b.ToTable("LookUpMappings");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.MaritalStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<int>("InstituteId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("Status");

                    b.HasKey("Id");

                    b.HasIndex("InstituteId");

                    b.ToTable("MaritalStatuses");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.MotherTongue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<int>("InstituteId");

                    b.Property<string>("Language")
                        .IsRequired();

                    b.Property<bool>("Status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("InstituteId");

                    b.ToTable("MotherTongues");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.Occupation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<int>("InstituteId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("Status");

                    b.HasKey("Id");

                    b.HasIndex("InstituteId");

                    b.ToTable("Occupations");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.Qualification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<int>("InstituteId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("Status");

                    b.HasKey("Id");

                    b.HasIndex("InstituteId");

                    b.ToTable("Qualifications");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.Relationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<int>("InstituteId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("Status");

                    b.HasKey("Id");

                    b.HasIndex("InstituteId");

                    b.ToTable("Relationships");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.Religion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<int>("InstituteId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("Status");

                    b.HasKey("Id");

                    b.HasIndex("InstituteId");

                    b.ToTable("Religions");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.ReligionCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<int>("InstituteId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("Status");

                    b.HasKey("Id");

                    b.HasIndex("InstituteId");

                    b.ToTable("ReligionCategories");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<int>("InstituteId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("Status");

                    b.HasKey("Id");

                    b.HasIndex("InstituteId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.SportDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<int>("InstituteId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("Status");

                    b.HasKey("Id");

                    b.HasIndex("InstituteId");

                    b.ToTable("SportDetails");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.StaffActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<DateTime>("EndDate");

                    b.Property<int>("InstituteId");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("StaffId");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("Id");

                    b.HasIndex("InstituteId");

                    b.HasIndex("StaffId");

                    b.ToTable("StaffActivities");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.StaffBasicPersonalInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AlternatePhoneNumber");

                    b.Property<int?>("BloodGroupId");

                    b.Property<int?>("CasteId");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<DateTime>("DateOfJoining");

                    b.Property<int>("DesignationId");

                    b.Property<string>("EmployeeId")
                        .IsRequired();

                    b.Property<string>("FamilyImage");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<int>("GenderId");

                    b.Property<string>("IdentificationMarks");

                    b.Property<int?>("InstituteId");

                    b.Property<bool>("IsArchived");

                    b.Property<bool>("IsPresentAddressIsSameAsPermanent");

                    b.Property<bool>("IsTeachingStaff");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<int>("MaritalStatus");

                    b.Property<string>("MiddleName");

                    b.Property<string>("MobileNumber")
                        .IsRequired();

                    b.Property<int?>("MotherTongueId");

                    b.Property<int?>("NationalityId");

                    b.Property<DateTime?>("PassportExpireDate");

                    b.Property<int?>("PassportIssuedCountryId");

                    b.Property<DateTime?>("PassportIssuedDate");

                    b.Property<string>("PassportNumber");

                    b.Property<string>("PermanentAddress")
                        .IsRequired();

                    b.Property<int>("PermanentCityId");

                    b.Property<string>("PermanentZipcode");

                    b.Property<string>("PersonalImage");

                    b.Property<string>("PresentAddress");

                    b.Property<int>("PresentCityId");

                    b.Property<string>("PresentZipcode");

                    b.Property<string>("Qualification");

                    b.Property<int?>("ReligionId");

                    b.Property<string>("SocialSecurityNumber");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("BloodGroupId");

                    b.HasIndex("CasteId");

                    b.HasIndex("DesignationId");

                    b.HasIndex("GenderId");

                    b.HasIndex("InstituteId");

                    b.HasIndex("MotherTongueId");

                    b.HasIndex("NationalityId");

                    b.HasIndex("PassportIssuedCountryId");

                    b.HasIndex("PermanentCityId");

                    b.HasIndex("PresentCityId");

                    b.HasIndex("ReligionId");

                    b.HasIndex("UserId");

                    b.ToTable("StaffBasicPersonalInformation");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.StaffDepartmentMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<int>("DepartmentId");

                    b.Property<int>("StaffId");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("StaffId");

                    b.ToTable("StaffDepartmentMappings");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.StaffExperienceMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("InstituteName")
                        .IsRequired();

                    b.Property<int>("StaffId");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.ToTable("StaffExperiences");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.StaffPlanner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime>("DateOfPlan");

                    b.Property<string>("Description");

                    b.Property<int>("InstituteId");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("StaffId");

                    b.HasKey("Id");

                    b.HasIndex("InstituteId");

                    b.HasIndex("StaffId");

                    b.ToTable("StaffPlanners");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.StudentAward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AwardName")
                        .IsRequired();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("InstituteName")
                        .IsRequired();

                    b.Property<int>("StudentId");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentAwards");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.StudentBasicInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AdmissionClassId");

                    b.Property<DateTime>("AdmissionDate");

                    b.Property<string>("AdmissionNumber")
                        .IsRequired();

                    b.Property<string>("AlternatePhoneNumber");

                    b.Property<int?>("BloodGroupId");

                    b.Property<int?>("CasteId");

                    b.Property<string>("ComingBy");

                    b.Property<string>("ComingPlace");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<int>("CurrentAcademicYearId");

                    b.Property<int>("CurrentClassId");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("FamilyRelationEmail");

                    b.Property<string>("FamilyRelationMobileNumber")
                        .IsRequired();

                    b.Property<string>("FamilyRelationMonthlyIncome");

                    b.Property<string>("FamilyRelationName")
                        .IsRequired();

                    b.Property<int?>("FamilyRelationOccupationId");

                    b.Property<int>("FamilyRelationType");

                    b.Property<string>("FeeChallanNumber")
                        .IsRequired();

                    b.Property<int>("FirstLanguageId");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<int>("GenderId");

                    b.Property<string>("IdentificationMarks");

                    b.Property<int?>("InstituteId");

                    b.Property<bool>("IsArchived");

                    b.Property<bool>("IsPhysicallyHandicapped");

                    b.Property<bool>("IsPresentAddressIsSameAsPermanent");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<int>("MaritalStatus");

                    b.Property<string>("MiddleName");

                    b.Property<string>("MobileNumber")
                        .IsRequired();

                    b.Property<string>("MotherName")
                        .IsRequired();

                    b.Property<int?>("MotherTongueId");

                    b.Property<int?>("NationalityId");

                    b.Property<DateTime?>("PassportExpireDate");

                    b.Property<int?>("PassportIssuedCountryId");

                    b.Property<DateTime?>("PassportIssuedDate");

                    b.Property<string>("PassportNumber");

                    b.Property<string>("PermanentAddress")
                        .IsRequired();

                    b.Property<int>("PermanentCityId");

                    b.Property<string>("PermanentZipcode");

                    b.Property<string>("PersonalImage");

                    b.Property<string>("PresentAddress");

                    b.Property<int>("PresentCityId");

                    b.Property<string>("PresentZipcode");

                    b.Property<int?>("RelievingClassId");

                    b.Property<DateTime?>("RelievingDate");

                    b.Property<string>("RelievingReason");

                    b.Property<int>("RelievingType");

                    b.Property<int?>("ReligionId");

                    b.Property<string>("RollNumber")
                        .IsRequired();

                    b.Property<string>("SchoolApplicationNumber");

                    b.Property<int>("SecondLanguageId");

                    b.Property<int>("Section");

                    b.Property<string>("SocialSecurityNumber");

                    b.Property<DateTime?>("TCDate");

                    b.Property<string>("TCNumber");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("AdmissionClassId");

                    b.HasIndex("BloodGroupId");

                    b.HasIndex("CasteId");

                    b.HasIndex("CurrentAcademicYearId");

                    b.HasIndex("CurrentClassId");

                    b.HasIndex("FamilyRelationOccupationId");

                    b.HasIndex("FirstLanguageId");

                    b.HasIndex("GenderId");

                    b.HasIndex("InstituteId");

                    b.HasIndex("MotherTongueId");

                    b.HasIndex("NationalityId");

                    b.HasIndex("PassportIssuedCountryId");

                    b.HasIndex("PermanentCityId");

                    b.HasIndex("PresentCityId");

                    b.HasIndex("RelievingClassId");

                    b.HasIndex("ReligionId");

                    b.HasIndex("SecondLanguageId");

                    b.HasIndex("UserId");

                    b.ToTable("StudentBasicInformation");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.StudentDiscipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Descriptiom")
                        .IsRequired();

                    b.Property<DateTime>("DisciplineDate");

                    b.Property<int>("StudentId");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentDisciplines");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.StudentPriorEducation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime>("FromDate");

                    b.Property<string>("InstituteName")
                        .IsRequired();

                    b.Property<int>("StudentId");

                    b.Property<DateTime>("ToDate");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentPriorEducations");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.StudentSport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<int>("LevelId");

                    b.Property<int>("SportId");

                    b.Property<int>("StudentId");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("SportId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentSports");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.TeachingStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<int>("InstituteId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("Status");

                    b.HasKey("Id");

                    b.HasIndex("InstituteId");

                    b.ToTable("TeachingStaffs");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("EmailBcc");

                    b.Property<string>("EmailSubject");

                    b.Property<string>("EmailTo");

                    b.Property<string>("Format");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("TemplateFormat");

                    b.Property<int>("TemplateTypeId");

                    b.Property<int>("UserGroupId");

                    b.HasKey("Id");

                    b.HasIndex("TemplateTypeId");

                    b.HasIndex("UserGroupId");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.TemplateType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<int>("InstituteId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("InstituteId");

                    b.ToTable("TemplateTypes");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.TimeTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AcademicYearId");

                    b.Property<int>("ClassId");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<int>("FirstBreakAfterPeriod");

                    b.Property<int>("FirstBreakDuration");

                    b.Property<int>("InstituteId");

                    b.Property<int>("PeriodCount");

                    b.Property<int>("PeriodDuration");

                    b.Property<string>("PeriodStartTime")
                        .IsRequired();

                    b.Property<int>("SecondBreakAfterPeriod");

                    b.Property<int>("SecondBreakDuration");

                    b.Property<int>("SectionId");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("ClassId");

                    b.HasIndex("InstituteId");

                    b.HasIndex("SectionId");

                    b.ToTable("TimeTables");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.TimeTableDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<int>("PeriodNumber");

                    b.Property<int>("SubjectId");

                    b.Property<int>("TimeTableId");

                    b.Property<int>("WeekDaysEnum");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TimeTableId");

                    b.ToTable("TimeTableDetails");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.UserGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<int?>("CompanyWbs");

                    b.Property<string>("CreatedByUserId");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description")
                        .HasMaxLength(200);

                    b.Property<int>("InstituteId");

                    b.Property<DateTime?>("LastUpdatedDate");

                    b.Property<string>("LastUpdatedUserId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("InstituteId");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.UserGroupFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("CanAdd");

                    b.Property<bool>("CanDelete");

                    b.Property<bool>("CanEdit");

                    b.Property<bool>("CanView");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<int>("UserGroupFeatureEnum");

                    b.Property<int>("UserGroupId");

                    b.HasKey("Id");

                    b.HasIndex("UserGroupId");

                    b.ToTable("UserGroupFeatures");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.UserGroupMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<int>("UserGroupId");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserGroupId");

                    b.HasIndex("UserId");

                    b.ToTable("UserGroupMapping");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.UserInstituteMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<int>("InstituteId");

                    b.Property<bool>("IsActive");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("InstituteId");

                    b.HasIndex("UserId");

                    b.ToTable("UserInstituteMappings");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.WeekOff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AcademicYearId");

                    b.Property<int?>("CompanyWbs");

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<int>("InstitutionId");

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<int>("WeekDay");

                    b.Property<int>("WeekNumber");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("WeekOffs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.AdministrationCity", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.AdministrationState", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.AdministrationCountry", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany("AdministrationCountries")
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.AdministrationCurrency", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany("AdministrationCurrencies")
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.AdministrationEmailConfiguration", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany()
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMS.DomainModel.Models.ApplicationUser", "UpdatedByuser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.AdministrationState", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.AdministrationCountry", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.AutoSequenceGenerator", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany()
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMS.DomainModel.Models.ApplicationUser", "UpdateBy")
                        .WithMany()
                        .HasForeignKey("UpdateById");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.AutoSequenceGeneratorDataType", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.AutoSequenceGenerator", "AutoSequenceGenerator")
                        .WithMany("AutoSequenceGeneratorDataTypes")
                        .HasForeignKey("AutoSequenceGeneratorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.BloodGroup", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany("BloodGroups")
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.Caste", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany("Castes")
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.Department", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany()
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMS.DomainModel.Models.ApplicationUser", "UpdatedByuser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.Designation", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany()
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMS.DomainModel.Models.ApplicationUser", "UpdatedByuser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");
                });

            modelBuilder.Entity("IMS.DomainModel.Models.Gender", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany("Genders")
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.Holiday", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.Institute", "AcademicYear")
                        .WithMany()
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMS.DomainModel.Models.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.InstituteAcademicYear", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany()
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.InstituteBccCcEmailMapping", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany("InstituteBccCcEmailMappings")
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.InstituteClass", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany("InstituteClasses")
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.InstituteClassSubjectMapping", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.StaffBasicPersonalInformation", "AlternateFaculty")
                        .WithMany()
                        .HasForeignKey("AlternateFacultyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMS.DomainModel.Models.InstituteClass", "InstituteClass")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMS.DomainModel.Models.StaffBasicPersonalInformation", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMS.DomainModel.Models.InstituteSubject", "InstituteSubject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.InstituteLanguageMaster", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany("InstituteLanguageMasters")
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.InstituteNationality", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany("InstituteNationalities")
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.InstituteRole", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany("InstituteRoles")
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.InstituteSubject", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany("InstituteSubjects")
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.Level", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany("Levels")
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.LookUp", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany("LookUps")
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.LookUpMapping", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.LookUp", "LookUp")
                        .WithMany("LookUpMappings")
                        .HasForeignKey("LookUpId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.MaritalStatus", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany()
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.MotherTongue", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany()
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.Occupation", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany("Occupations")
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.Qualification", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany("Qualifications")
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.Relationship", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany("Relationships")
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.Religion", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany("Religions")
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.ReligionCategory", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany("ReligionCategories")
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.Section", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany()
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.SportDetail", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany("SportDetails")
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.StaffActivity", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany()
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMS.DomainModel.Models.StaffBasicPersonalInformation", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.StaffBasicPersonalInformation", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.BloodGroup", "BloodGroup")
                        .WithMany()
                        .HasForeignKey("BloodGroupId");

                    b.HasOne("IMS.DomainModel.Models.Caste", "Caste")
                        .WithMany()
                        .HasForeignKey("CasteId");

                    b.HasOne("IMS.DomainModel.Models.Designation", "Designation")
                        .WithMany()
                        .HasForeignKey("DesignationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMS.DomainModel.Models.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany()
                        .HasForeignKey("InstituteId");

                    b.HasOne("IMS.DomainModel.Models.MotherTongue", "MotherTongue")
                        .WithMany()
                        .HasForeignKey("MotherTongueId");

                    b.HasOne("IMS.DomainModel.Models.InstituteNationality", "Nationality")
                        .WithMany()
                        .HasForeignKey("NationalityId");

                    b.HasOne("IMS.DomainModel.Models.AdministrationCountry", "PassportIssuedCountry")
                        .WithMany()
                        .HasForeignKey("PassportIssuedCountryId");

                    b.HasOne("IMS.DomainModel.Models.AdministrationCity", "PermanentCity")
                        .WithMany()
                        .HasForeignKey("PermanentCityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMS.DomainModel.Models.AdministrationCity", "PresentCity")
                        .WithMany()
                        .HasForeignKey("PresentCityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMS.DomainModel.Models.Religion", "Religion")
                        .WithMany()
                        .HasForeignKey("ReligionId");

                    b.HasOne("IMS.DomainModel.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.StaffDepartmentMapping", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMS.DomainModel.Models.StaffBasicPersonalInformation", "Staff")
                        .WithMany("StaffDepartments")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.StaffExperienceMapping", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.StaffBasicPersonalInformation", "Staff")
                        .WithMany("StaffExperiences")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.StaffPlanner", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany()
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMS.DomainModel.Models.StaffBasicPersonalInformation", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.StudentAward", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.StudentBasicInformation", "Student")
                        .WithMany("StudentAwards")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.StudentBasicInformation", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.InstituteClass", "AdmissionClass")
                        .WithMany()
                        .HasForeignKey("AdmissionClassId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMS.DomainModel.Models.BloodGroup", "BloodGroup")
                        .WithMany()
                        .HasForeignKey("BloodGroupId");

                    b.HasOne("IMS.DomainModel.Models.Caste", "Caste")
                        .WithMany()
                        .HasForeignKey("CasteId");

                    b.HasOne("IMS.DomainModel.Models.InstituteAcademicYear", "CurrentAcademicYear")
                        .WithMany()
                        .HasForeignKey("CurrentAcademicYearId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMS.DomainModel.Models.InstituteClass", "CurrentClass")
                        .WithMany()
                        .HasForeignKey("CurrentClassId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMS.DomainModel.Models.Occupation", "FamilyRelationOccupation")
                        .WithMany()
                        .HasForeignKey("FamilyRelationOccupationId");

                    b.HasOne("IMS.DomainModel.Models.InstituteLanguageMaster", "FirstLanguage")
                        .WithMany()
                        .HasForeignKey("FirstLanguageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMS.DomainModel.Models.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany()
                        .HasForeignKey("InstituteId");

                    b.HasOne("IMS.DomainModel.Models.MotherTongue", "MotherTongue")
                        .WithMany()
                        .HasForeignKey("MotherTongueId");

                    b.HasOne("IMS.DomainModel.Models.InstituteNationality", "Nationality")
                        .WithMany()
                        .HasForeignKey("NationalityId");

                    b.HasOne("IMS.DomainModel.Models.AdministrationCountry", "PassportIssuedCountry")
                        .WithMany()
                        .HasForeignKey("PassportIssuedCountryId");

                    b.HasOne("IMS.DomainModel.Models.AdministrationCity", "PermanentCity")
                        .WithMany()
                        .HasForeignKey("PermanentCityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMS.DomainModel.Models.AdministrationCity", "PresentCity")
                        .WithMany()
                        .HasForeignKey("PresentCityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMS.DomainModel.Models.InstituteClass", "RelievingClass")
                        .WithMany()
                        .HasForeignKey("RelievingClassId");

                    b.HasOne("IMS.DomainModel.Models.Religion", "Religion")
                        .WithMany()
                        .HasForeignKey("ReligionId");

                    b.HasOne("IMS.DomainModel.Models.InstituteLanguageMaster", "SecondLanguage")
                        .WithMany()
                        .HasForeignKey("SecondLanguageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMS.DomainModel.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.StudentDiscipline", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.StudentBasicInformation", "Student")
                        .WithMany("StudentDisciplines")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.StudentPriorEducation", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.StudentBasicInformation", "Student")
                        .WithMany("StudentPriorEducations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.StudentSport", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMS.DomainModel.Models.SportDetail", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMS.DomainModel.Models.StudentBasicInformation", "Student")
                        .WithMany("StudentSports")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.TeachingStaff", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany()
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.Template", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.TemplateType", "TemplateType")
                        .WithMany()
                        .HasForeignKey("TemplateTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMS.DomainModel.Models.UserGroup", "UserGroup")
                        .WithMany()
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.TemplateType", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany()
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.TimeTable", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.InstituteAcademicYear", "AcademicYear")
                        .WithMany()
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMS.DomainModel.Models.InstituteClass", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany()
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMS.DomainModel.Models.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.TimeTableDetails", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.InstituteSubject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMS.DomainModel.Models.TimeTable", "TimeTable")
                        .WithMany()
                        .HasForeignKey("TimeTableId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.UserGroup", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany()
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.UserGroupFeature", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.UserGroup", "UserGroup")
                        .WithMany("UserGroupFeatures")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.UserGroupMapping", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.UserGroup", "UserGroup")
                        .WithMany()
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMS.DomainModel.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.UserInstituteMapping", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.Institute", "Institute")
                        .WithMany("UserInstituteMappings")
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMS.DomainModel.Models.ApplicationUser", "User")
                        .WithMany("UserInstituteMappings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMS.DomainModel.Models.WeekOff", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.Institute", "AcademicYear")
                        .WithMany()
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMS.DomainModel.Models.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMS.DomainModel.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("IMS.DomainModel.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
